version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis
      - ollama  # Ollama'yı da beklemesini söylüyoruz

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"  # Ollama'nın varsayılan portu
    volumes:
      - ollama-data:/root/.ollama  # Ollama'nın model verileri için kalıcı depolama

volumes:
  ollama-data:
