from django.core.management.base import BaseCommand
from item.models import BaseIngredient

class Command(BaseCommand):
    help = "Populate base ingredients in the database"

    BASE_INGREDIENT_NAMES = [
    "1,2-Hexanediol",
    "2-Hexanediol",
    "3-Butanediol",
    "3-O-Ethyl Ascorbic Acid",
    "Cetearyl Alcohol",
    "7-Dehydrocholesterol",
    "Abies",
    "Acacia Senegal Gum",
    "Acer Saccharum Extract",
    "Acetone",
    "Acetyl Dipeptide-1 Cetyl Ester",
    "Acetyl Glucosamine",
    "Acetyl Glutamine",
    "Acetyl Heptapeptide-4",
    "Acetyl Tetrapeptide-11",
    "Acetyl Tetrapeptide-9",
    "Achillea Millefolium Extract",
    "Acorus",
    "Acrylates/C10-30 Alkyl Acrylate Crosspolymer",
    "Acrylates Copolymer",
    "Acrylates/Polytrimethylsiloxymethacrylate Copolymer",
    "Acrylates/Stearyl Methacrylate Copolymer",
    "Actinidia Chinensis Extract",
    "Adansonia Digitata Pulp Extract",
    "Adansonia Digitata Seed Oil",
    "Adenosine",
    "Adenosine + Madecassoside",
    "Agar",
    "Ahnfeltiopsis Concinna Extract",
    "Alanine",
    "Alaria Esculenta Extract",
    "Alchemilla Vulgaris Leaf Extract",
    "Alcohol",
    "Alcohol Denat.",
    "Algae Extract",
    "Algin",
    "Alkyl Cetearyl Dimethicone Crosspolymer",
    "Allantoin",
    "Aloe Barbadensis Leaf Juice",
    "Aloe Barbadensis Flower Extract",
    "Aloe Barbadensis Leaf Juice Powder",
    "Alpha-Arbutin",
    "Alpha-Isomethyl Ionone",
    "Aluminium Sucrose Octasulfate",
    "Aluminum Hydroxide",
    "Amber Powder",
    "Amethyst Powder",
    "Ammonium Acryloyldimethyltaurate",
    "Ammonium Acryloyldimethyltaurate/VP Copolymer",
    "Amylopectin",
    "Ananas Sativus Extract",
    "Anhydroxylitol",
    "Anthemis Nobilis Flower Extract",
    "Aqua",
    "Arachidyl Alcohol",
    "Arachidyl Glucoside",
    "Arbutus Unedo Fruit Extract",
    "Arctium Lappa Root Extract",
    "Arctostaphylos Uva-Ursi Leaf Extract",
    "Argania Spinosa Kernel Oil",
    "Arginine",
    "Arnica Montana Flower Extract",
    "Aroma",
    "Artemisia Princeps Leaf Extract",
    "Ascorbic Acid",
    "Ascorbyl Glucoside",
    "Ascorbyl Palmitate",
    "Ascorbyl Tetraisopalmitate",
    "Asiatic Acid",
    "Asiaticoside",
    "Aspartic Acid",
    "Avena Sativa Kernel Extract",
    "Avena Sativa Kernel Flour",
    "Avene Thermal Spring Water",
    "Averrhoa Carambola Fruit Extract",
    "Avobenzone",
    "Azelaic Acid",
    "Bacillus/Soybean Ferment Extract",
    "Backhousia Citriodora Leaf Extract",
    "Balanites",
    "Baptisia Tinctoria Root Extract",
    "Barium Sulfate",
    "Barosma Betulina Leaf Extract",
    "Beer",
    "Beeswax",
    "Beeswax (Cera Alba)",
    "Begonia",
    "Beheneth-20",
    "Behenic Acid",
    "Behenyl Alcohol",
    "Belamcanda Chinensis Root Extract",
    "Bellis Perennis (Daisy) Flower",
    "Bentonite",
    "Benzalkonium Chloride",
    "Benzoic Acid",
    "Benzophenone-4",
    "Benzotriazolyl Dodecyl p-Cresol",
    "Benzyl Alcohol",
    "Benzyl Benzoate",
    "Benzyl Cinnamate",
    "Benzyl Salicylate",
    "Berberis Vulgaris Root Extract",
    "Beta-Carotene",
    "Beta-Glucan",
    "Betaine",
    "Betaphycus Gelatinum Extract",
    "Beta- Sitosterol",
    "BHT",
    "Bidens Pilosa Extract",
    "Bioflavonoids",
    "Biosaccharide Gum-1",
    "Biosaccharide Gum-2",
    "Biosaccharide Gum-4",
    "Bisabolol",
    "Bis-Diglyceryl Polyacryladipate-2",
    "Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine",
    "Bis-Hydroxyethoxypropyl Dimethicone",
    "Bis-Peg-18 Methyl Ether Dimethyl Silane",
    "Blue 1 (Ci 42090)",
    "Borago Officinalis Seed Oil",
    "Boswellia Serrata Extract",
    "Brassica Campestris/Aleurites Fordi Oil Copolymer",
    "Brassica Campestris (Rapeseed) Sterols",
    "Broccoli Seed Oil Polyglyceryl-4 Esters",
    "Butil Metoksidibenzoilmetan",
    "Butylene/Ethylene/Styrene Copolymer",
    "Butylene Glycol",
    "Butyl Methoxydibenzoylmethane",
    "Butyloctyl Salicylate",
    "Butyrospermum Parkii Butter",
    "Butyrospermum Parkii Butter (Shea Butter)",
    "Butyrospermum Parkii (Shea) Butter Extract",
    "Butyrospermum Parkii Shea Butter Fruit",
    "Butyrospermum Parkii (Shea) Oil",
    "C10-18 Triglycerides",
    "C12-13 Alkyl Lactate",
    "C12-15 Alkyl Benzoate",
    "C12-16 Alcohols",
    "C12-20 Alkyl Glucoside",
    "C12-22 Alkyl Acrylate/Hydroxyethylacrylate Copolymer",
    "C13-15 Alkane",
    "C14-22 Alcohols",
    "C15-19 Alkane",
    "C 18-38 Alkyl Hydroxystearol Stearate",
    "C20-40 Alkyl Stearate",
    "C9-12 Alkane",
    "Caesalpinia Spinosa Fruit Extract",
    "Caffeine",
    "Calcium Gluconate",
    "Calcium Sodium Borosilicate",
    "Calendula Officinalis Extract",
    "Calendula Officinalis Flower Extract",
    "Calophyllum Inophyllum Seed Oil",
    "Camelia Sinensis Leaf Extract",
    "Camelina Sativa Seed Oil",
    "Camellia Japonica Flower Extract",
    "Camellia Japonica Leaf Extract",
    "Camellia Oleifera Leaf Extract",
    "Camellia Oleifera Seed Oil",
    "Camellia Sinensis (Green Tea) Leaf Extract",
    "Camellia Sinensis (Purple Tea) Leaf Extract",
    "Camellia Sinensis Seed Extract",
    "Camellia SinensisPhenoxyethanol",
    "Camphor",
    "Cananga Odorata Flower Extract",
    "Cananga Odorata Flower Oil",
    "Candelilla Cera Wax",
    "Canola Oil",
    "Capric",
    "Caprooyl Phytosphingosine",
    "Caprooyl Sphingosine",
    "Caprylhydroxamic Acid",
    "Caprylic",
    "Caprylic/Capric/Myristic/Stearic Triglyceride",
    "Caprylic/Capric/Succinic Triglyceride",
    "Caprylic/Capric Triglyceride",
    "Capryloyl Glycerin/Sebacic Acid Copolymer",
    "Capryloyl Glycine",
    "Caprylyl Caprylate/Caprate",
    "Caprylyl/Capryl Glucoside",
    "Caprylyl Glycol",
    "Caprylyl Methicone",
    "Caramel",
    "Carbomer",
    "Carbon Dioxide",
    "Cardiospermum Halicacabum Flower/Leaf/Vine Extract",
    "Carica Papaya (Papaya) Fruit Extract",
    "Carnauba Copernicia Cerifera Carnauba Wax",
    "Carrageenan",
    "Carthamus Tinctorius Oleosomes",
    "Carthamus Tinctorius (Safflower) Oleosomes",
    "Carthamus Tinctorius (Safflower) Seed Oil",
    "Castor Oil/IPDI Copolymer",
    "Cedar",
    "Cellulose",
    "Cellulose Gum",
    "Centella Asiatica Extract",
    "Centella Asiatica Leaf Extract",
    "Centella Asiatica Leaf Water",
    "Centella Asiatica Root Extract",
    "Cera Alba",
    "Cera Microcristallina Microcrystalline Wax",
    "Ceramide",
    "Ceramide 3",
    "Ceramide AP",
    "Ceramide EOP",
    "Ceramide EOS",
    "Ceramide NG",
    "Ceramide NP",
    "Ceramide NS",
    "Ceramides",
    "Ceteareth-12",
    "Ceteareth-20",
    "Ceteareth-25",
    "Cetearyl Alcohol",
    "Cetearyl Ethylhexanoate",
    "Cetearyl Glucoside",
    "Cetearyl Olivate",
    "Ceteth-3",
    "Ceteth-5",
    "Cetrimonium Bromide",
    "Cetyl Alcohol",
    "Cetyl Ethylhexanoate",
    "Cetyl Lactate",
    "Cetyl Palmitate",
    "Chaenomeles Sinensis Fruit Extract",
    "Chamomilla Recutita (Matricaria) Flower Extract",
    "Chenopodium Quinoa Seed Extract",
    "Chlorella Vulgaris Extract",
    "Chlorophyllin-Copper Complex",
    "Chlorphenesin",
    "Cholesterol",
    "Chondrus Crispus",
    "Chondrus Crispus (Carrageenan) Extract",
    "Chromium Oxide Greens (CI 77288)",
    "CI 17200 (Red 33)",
    "CI 42090 (Blue 1)",
    "CI 73360 (Red 30)",
    "CI 77492 (Iron Oxides)",
    "CI 77891 (Titanium Dioxide)",
    "Citral",
    "Citric Acid",
    "Citrullus Lanatus (Watermelon) Fruit Extract",
    "Citrullus Lanatus (Watermelon) Seed Extract",
    "Citrullus Lanatus (Watermelon) Seed Oil",
    "Citrus Aurantifolia (Lime) Juice",
    "Citrus Aurantifolia (Lime) Oil",
    "Citrus Aurantium Amara (Bitter Orange) Flower Oil",
    "Citrus Aurantium Amara (Bitter Orange) Flower Water",
    "Citrus Aurantium Amara (Bitter Orange) Fruit Extract",
    "Citrus Aurantium Bergamia (Bergamot) Fruit Oil",
    "Citrus Aurantium Dulcis (Orange) Callus Culture Extract",
    "Citrus Aurantium Dulcis (Orange) Fruit Extract",
    "Citrus Aurantium Dulcis (Orange) Juice",
    "Citrus Aurantium Dulcis (Orange) Oil",
    "Citrus Aurantium Dulcis (Orange) Peel Extract",
    "Citrus Aurantium Dulcis (Orange) Peel Oil",
    "Citrus Aurantium Sinensis Peel Extract",
    "Citrus Grandis (Grapefruit) Peel Oil",
    "Citrus Limon (Lemon) Fruit Extract",
    "Citrus Limon (Lemon) Fruit Oil",
    "Citrus Limon (Lemon) Peel Oil",
    "Citrus Medica Limonum (Lemon) Juice",
    "Citrus Medica Limonum (Lemon) Peel Oil",
    "Citrus Nobilis (Mandarin Orange) Peel Oil",
    "Citrus Paradisi (Grapefruit) Fruit Extract",
    "Citrus Reticulata (Tangerine) Fruit Extract",
    "Citrus Reticulata (Tangerine) Leaf Oil",
    "Citrus Reticulata (Tangerine) Peel Extract",
    "Citrus Sinensis Peel Oil",
    "Citrus Unshiu Peel Extract",
    "Cl 7492",
    "Cladosiphon Okamuranus Extract",
    "Cocamidopropyl Betaine",
    "Cocamidopropyl Hydroxysultaine",
    "Coccinia Indica Fruit Extract",
    "Coco-Betaine",
    "Coco-Caprylate",
    "Coco-Caprylate/Caprate",
    "Coco-Glucoside",
    "Coconut Acid",
    "Coconut Alkanes",
    "Cocos Nucifera (Coconut) Oil",
    "Coix Lacryma-Jobi Ma-Yuen Seed Extract",
    "Colloidal Oatmeal",
    "Commiphora Myrrha Resin Extract",
    "Copernicia Cerifera Cera",
    "Copernicia Cerifera Wax",
    "Copper Gluconate",
    "Copper Sulfate",
    "Copper Tripeptide-1",
    "Coptis Japonica Root Extract",
    "Corallina Officinalis Extract",
    "Corylus Avellana (Hazel) Seed Oil",
    "Coumarin",
    "Crataegus Cuneata Fruit Extract",
    "Crithmum Maritimum Extract",
    "Crocus Chrysanthus Bulb Extract",
    "Cucumis Melo Cantalupensis Fruit Extract",
    "Cucumis Melo (Melon) Fruit Extract",
    "Cucumis Sativus (Cucumber) Fruit Extract",
    "Cupressus Sempervirens Leaf Oil",
    "Curcuma Longa (Turmeric) Leaf Extract",
    "Curcuma Longa (Turmeric) Root Extract",
    "Cyclodextrin",
    "Cyclohexasiloxane",
    "Cyclopentasiloxane",
    "Cymbopogon Martini Oil",
    "Damar",
    "Daucus",
    "Daucus Carota Sativa (Carrot) Root Extract",
    "Davidsonia Jerseyana Fruit Extract",
    "Decyl Glucoside",
    "Dehydroacetic Acid",
    "Dextran",
    "Dextrin",
    "Dextrin Palmitate",
    "Dibutyl Adipate",
    "Dibutyl Ethylhexanol Glutamide",
    "Dibutyl Lauroyl Glutamide",
    "Dicaprylyl Carbonate",
    "Dicaprylyl Ether",
    "Diethylamino Hydroxybenzoyl Hexyl Benzoate",
    "Diethylhexyl Syringylidenemalonate",
    "Dihydroxyacetone",
    "Diisopropyl Adipate",
    "Diisostearyl Malate",
    "Dilauryl Citrate",
    "Dilauryl Thiodipropionate",
    "Dilinoleic Acid/Butanediol Copolymer",
    "Dilinoleic Acid/Propanediol Copolymer",
    "Dimethicone",
    "Dimethicone Crosspolymer",
    "Dimethicone/Vinyl Dimethicone Crosspolymer",
    "Dimethiconol",
    "Dimethyl Isosorbide",
    "Dimethylmethoxy Chromanyl Palmitate",
    "Dipalmitoyl Hydroxyproline",
    "Dipentaerythrityl Tetrahydroxystearate",
    "Dipentaerythrityl Hexahydroxystearate",
    "Diphenylsiloxy Phenyl Trimethicone",
    "Dipotassium Glycyrrhizate",
    "Dipropylene Glycol",
    "Dipsacus Sylvestris Extract",
    "Disiloxane",
    "Disodium Cocoamphodiacetate",
    "Disodium Cocoyl Glutamate",
    "Disodium EDTA",
    "Disodium Edta-Copper",
    "Disodium Phosphate",
    "Disteardimonium Hectorite",
    "Disuccinate",
    "dl-alpha Tocopheryl Acetate",
    "Dodecane/Coconut Alkanes",
    "Dunaliella Salina Extract",
    "Echinacea Purpurea Extract",
    "Echinacea Purpurea Root Extract",
    "Echium Plantagineum Seed Oil",
    "Eclipta Prostrata Extract",
    "Ectoin",
    "Elaeis Guineensis Oil",
    "Elastin",
    "Elettaria Cardamomum Seed Extract",
    "Engelhardtia Chrysolepis Leaf Extract",
    "Ensulizole",
    "Enteromorpha Compressa Extract",
    "Epilobium Fleischeri (Alpine Willowherb) Flower/Leaf/Stem Extract",
    "Equisetum Arvense Leaf Extract",
    "Ergothioneine",
    "Eriobotrya Japonica Leaf Extract",
    "Eryngium Maritimum Extract",
    "Erythritol",
    "Ethanolamine",
    "Ethoxydiglycol",
    "Ethylhexylglycerin",
    "Ethylene Brassylate",
    "Ethylene/Propylene Copolymer",
    "Ethyl Ferulate",
    "Ethylhexyl Methoxycinnamate",
    "Ethylhexyl Methoxycrylene",
    "Ethylhexyl Palmitate",
    "Ethylhexyl Salicylate",
    "Ethylhexyl Triazone",
    "Eucalyptus Globulus Leaf Oil",
    "Eugenia Caryophyllus (Clove) Flower Oil",
    "Eugenol",
    "Euphorbia Cerifera (Candelilla) Wax",
    "Euterpe Oleracea Fruit Extract",
    "Farnesol",
    "Ferulic Acid",
    "Ficus Carica (Fig) Fruit Extract",
    "Flavor",
    "Flavor/Aroma",
    "Fluorosilicate",
    "Foeniculum Vulgare (Fennel) Oil",
    "Folic Acid",
    "Fragrance/Parfum",
    "Fragrance/Parfum 100% Naturally Derived",
    "Free Radicals",
    "Fructooligosaccharides",
    "Fructose",
    "Furcellaria Lumbricalis Extract",
    "Galactoarabinan",
    "Garcinia Mangostana Bark Extract",
    "Gellan Gum",
    "Gentiana Lutea Extract",
    "Geraniol",
    "Geranium Maculatum Oil",
    "Ginkgo Biloba",
    "Ginkgo Biloba Leaf Extract",
    "Gliseril Risinoleat",
    "Glucomannan",
    "Gluconolactone",
    "Glucose",
    "Glutathione",
    "Gluthathione",
    "Glycereth-26",
    "Glycerin",
    "Glyceryl Behenate",
    "Glyceryl Caprylate",
    "Glyceryl Citrate/Lactate/Linoleate/Oleate",
    "Glyceryl Cocoate",
    "Glyceryl Dibehenate",
    "Glyceryl Dioleate",
    "Glyceryl Glucoside",
    "Glyceryl Laurate",
    "Glyceryl Oleate",
    "Glyceryl Oleate Citrate",
    "Glyceryl Stearate",
    "GlycerylStearate",
    "Glyceryl Stearate Citrate",
    "Glyceryl Stearate SE",
    "Glyceryl Undecylenate",
    "Glycine",
    "Glycine Soja Oil / Soybean Oil",
    "Glycine Soja Oil/Soybean Oil",
    "Glycine Soja (Soybean) Oil",
    "Glycine Soja (Soybean) Seed Extract",
    "Glycine Soja (Soybean) Sterols",
    "Glycol Distearate",
    "Glycolic Acid",
    "Glycolipids",
    "Glycol Stearate",
    "Glycoproteins",
    "Glycyrrhiza Glabra (Licorice) Root Extract",
    "Glycyrrhiza Glabra Root Extract",
    "Glycyrrhiza Uralensis (Licorice) Root Extract",
    "Gold",
    "Gossypium Herbaceum (Cotton) Seed Oil",
    "Green 5 (CI 61570)",
    "Guar Gum",
    "Haematococcus Pluvialis Extract",
    "Hamamelis Virginiana",
    "Hamamelis Virginiana (Witch Hazel)",
    "Hamamelis Virginiana (Witch Hazel) Leaf Extract",
    "Hamamelis Virginiana (Witch Hazel) Water",
    "Hdi/Trimethylol Hexyllactone Crosspolymer",
    "Hectorite",
    "Hedychium Coronarium Root Extract",
    "Helianthus Annuus Seed Oil",
    "Helianthus Annuus Seed Oil / Sunflower Seed Oil",
    "Helianthus Annuus (Sunflower) Extract",
    "Helianthus Annuus (Sunflower) Seed Oil",
    "Helianthus Annuus (Sunflower) Seed Oil Unsaponifiables",
    "Helianthus Annuus (Sunflower) Seed Wax",
    "Helianthus Annuus (Sunflower) Sprout Extract",
    "Heptyl Undecylenate",
    "Hexapeptide-11",
    "Hexyl Cinnamal",
    "Hexylene Glycol",
    "Hexyl Laurate",
    "Histidine",
    "Homosalate",
    "Honey Extract / Mel / Extrait Demiel",
    "Houttuynia Cordata Extract",
    "Hovenia Dulcis Fruit Extract",
    "Hyaluronate",
    "Hyaluronic Acid",
    "Hydrated Silica",
    "Hydrogenated Castor Oil",
    "Hydrogenated Coconut Oil",
    "Hydrogenated Lecithin",
    "Hydrogenated Microcrystalline Wax",
    "Hydrogenated Olive Oil Unsaponifiables",
    "Hydrogenated Palm Glycerides Citrate",
    "Hydrogenated Palm Kernel Glycerides",
    "Hydrogenated Poly(C6-20 Olefin)",
    "Hydrogenated Polydecene",
    "Hydrogenated Polyisobutene",
    "Hydrogenated Vegetable Oil",
    "Hydrolyzed Algin",
    "Hydrolyzed Hyaluronic Acid",
    "Hydrolyzed Rice Protein",
    "Hydrolyzed Sodium Hyaluronate",
    "Hydroxyacetophenone",
    "Hydroxycitronellal",
    "Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer",
    "Hydroxyethylcellulose",
    "Hydroxyethylpiperazine Ethane Sulfonic Acid",
    "Hydroxypalmitoyl Sphinganine",
    "Hydroxyproline",
    "Hydroxyproline Palmitamide",
    "Hydroxypropylcellulose",
    "Hydroxypropyl Cyclodextrin",
    "Hydroxypropyl Methylcellulose Stearoxy Ether",
    "Hydroxypropyl Starch Phosphate",
    "Hydroxypropyltrimonium Hyaluronate",
    "Hydroxypropyltrimonium Maltodextrin Crosspolymer",
    "Hydroxystearic Acid",
    "Hydroxystearic/Linolenic/Oleic Polyglycerides",
    "Hypochlorous Acid",
    "Inactive Ingredients: C13-15 Alkane",
    "Inactive Ingredients: Water",
    "Inactive: Water (Aqua)",
    "Inositol",
    "Inulin",
    "Inulin Lauryl Carbamate",
    "Ionized Water",
    "Ipomoea Batatas (Purple Sweet Potato) Root Extract",
    "Iron Oxides",
    "Iron Oxides (CI 77491)",
    "Iron Oxides (CI 77492)",
    "Iron Oxides (CI 77499)",
    "Isoamyl p-Methoxycinnamate",
    "Isoceteth-20",
    "Isodecyl Neopentanoate",
    "Isododecane",
    "Isohexadecane",
    "Isoleucine",
    "Isononyl Isononanoate",
    "Isopentyldiol",
    "Isopropyl Isostearate",
    "Isopropyl Myristate",
    "Isopropyl Palmitate",
    "Isostearic Acid",
    "Isostearyl Alcohol",
    "Isostearyl Isostearate",
    "Jasminum Officinale (Jasmine) Flower/Leaf Extract",
    "Jojoba Esters",
    "Jojoba Oil",
    "Jojoba Oil/Macadamia Seed Oil Esters",
    "Juniperus Communis Fruit Extract",
    "Kappaphycus Alvarezii Extract",
    "Kojic Acid Dipalmitate",
    "Lactic Acid",
    "Lactobacillus Ferment",
    "Lactobacillus Ferment Lysate",
    "Lactobacillus ferment lysate extract",
    "Lactobacillus/Punica Granatum Fruit Ferment Extract",
    "Lactobacillus/Watermelon Fruit Ferment Extract",
    "Laminaria",
    "Laminaria Digitata Extract",
    "Laminaria Ochroleuca Extract",
    "Lanolin",
    "Lapsana Communis Flower/Leaf/Stem Extract",
    "Laureth-2",
    "Lauroyl Lysine",
    "Lauryl Glucoside",
    "Lauryl Laurate",
    "Lauryl Peg-9 Polydimethylsiloxyethyl Dimethicone",
    "Lauryl Polyglyceryl-3 Polydimethylsiloxyethyl Dimethicone",
    "Lavandula Angustifolia Flower Extract",
    "Lavandula Angustifolia (Lavender) Flower/Leaf/Stem Extract",
    "Lavandula Angustifolia (Lavender) Oil",
    "Leaf Extract",
    "Lecithin",
    "Lens Esculenta (Lentil) Fruit Extract",
    "Leontopodium Alpinum Flower/Leaf Extract",
    "Leuconostoc Ferment Filtrate",
    "Leuconostoc/Radish Root Ferment Filtrate",
    "Licorice Root Extract",
    "Limnanthes Alba (Meadowfoam) Seed Oil",
    "Limnanthes Alba Seed Oil",
    "Limonene",
    "Limonene [N4905/A]",
    "Limonene (*Natural Flavor / Arôme Naturel)",
    "Linalool",
    "Linalool (010/035)",
    "Linoleic Acid",
    "Linolenic Acid",
    "Linum Usitatissimum (Linseed) Seed Oil",
    "Lithothamnion Calcareum Extract",
    "Lonicera Japonica (Honeysuckle) Flower Extract",
    "Luffa Cylindrica Fruit/Leaf/Stem Extract",
    "Macadamia Ternifolia Seed Oil",
    "Madecassic Acid",
    "Madecassoside",
    "Magnesium Aluminum Silicate",
    "Magnesium Aspartate",
    "Magnesium Sulfate",
    "Malachite Extract",
    "Malic Acid",
    "Malpighia Glabra (Acerola) Fruit Juice",
    "Malpighia Punicifolia (Acerola) Fruit Extract",
    "Maltodextrin",
    "Malva Sylvestris (Mallow) Flower Extract",
    "Mangifera Indica (Mango) Seed Butter",
    "Mannitol",
    "Maris Aqua (Sea Water)",
    "Maris Sal/Sea Salt/Sel Marin",
    "Marrubium Vulgare Extract",
    "Mauritia Flexuosa Fruit Oil",
    "Meadowfoam Estolide",
    "Meadowfoam Seed Oil",
    "Melatonin",
    "Mel/Honey",
    "Melia Azadirachta Extract",
    "Melia Azadirachta Flower Extract",
    "Melia Azadirachta Leaf Extract",
    "Melissa Officinalis (Balm Mint) Leaf Oil",
    "Melissa Officinalis Leaf Extract",
    "Mentha Arvensis Leaf Oil",
    "Mentha Piperita Flower/Stem/Leaf Oil",
    "Mentha Piperita Oil",
    "Mentha Piperita (Peppermint) Oil",
    "Mentha Viridis (Spearmint) Leaf Oil",
    "Menthol",
    "Menthoxypropanediol",
    "Menthyl Lactate",
    "Methicone",
    "Methyl Dihydroabietate",
    "Methyl Gluceth-20",
    "Methyl Glucose Sesquistearate",
    "Methyl Methacrylate Crosspolymer",
    "Methylparaben",
    "Methylpropanediol",
    "Methyl Salicylate",
    "Methyl Trimethicone",
    "Mica",
    "Microcrystalline Cellulose",
    "Microcrystalline Wax",
    "Mineral Oil",
    "Mineral Oil (Paraffinum Liquidum)",
    "Morinda Citrifolia Fruit Extract",
    "Moringa Oleifera Seed Extract",
    "Moringa Oleifera Seed Oil",
    "Moringa Pterygosperma Seed Extract",
    "Myristic Acid",
    "Myristyl Malate Phosphonic Acid",
    "Myristyl Myristate",
    "Myrothamnus Flabellifolia Leaf Extract",
    "Nasturtium Officinale Flower/Leaf Extract",
    "Neopentyl Glycol Dicaprylate/Dicaprate",
    "Nepeta Cataria Extract",
    "Niacinamide",
    "Non-aerosol sunscreen body spray that’s water- & sweat-resistant & leaves skin looking healthy and protected.",
    "Nuxe Reve de Miel Dudak Balı'nın İçindekiler: Octyldodecanol",
    "Nylon-12",
    "Ocimum Basilicum (Basil) Flower/Leaf Extract",
    "Ocimum Sanctum Leaf Extract",
    "Octisalate",
    "Octocrylene",
    "Octocrylene 10.0%",
    "Octocrylene 10% Inactive: C12-15 Alkyl Benzoate",
    "Octyldodecanol",
    "Octyldodecyl Oleate",
    "Octyldodecyl Stearoyl Stearate",
    "O-Cymen-5-Ol",
    "Oil-free sunscreen for triple action and protection from UVA and UVB rays",
    "Olea Europaea Fruit Oil / Olive Fruit Oil",
    "Olea Europaea (Olive) Fruit Oil",
    "Oleic Acid",
    "Oleic/Linoleic/Linolenic Polyglycerides",
    "Oligopeptide-1",
    "Oligopeptide-2",
    "Oligopeptide-3",
    "Olus Oil (Vegetable Oil)",
    "Ophiopogon Japonicus Root Extract",
    "Opuntia Coccinellifera Fruit Extract",
    "Opuntia Ficus-Indica Stem Extract",
    "Orchid Extract",
    "Origanum Majorana Leaf Extract",
    "Oryza Sativa",
    "Oryza Sativa Bran Oil / Rice Bran Oil",
    "Oryza Sativa Cera/Oryza Sativa (Rice) Bran Wax",
    "Oryza Sativa (Purple Rice) Hull Extract",
    "Oryza Sativa (Rice) Bran Extract",
    "Oryza Sativa (Rice) Bran Oil",
    "Oryza Sativa (Rice) Bran Wax",
    "Oryza Sativa (Rice) Extract",
    "Oryza Sativa (Rice) Germ Extract",
    "Oryza Sativa (Rice) Powder",
    "Ozokerite",
    "Paeonia Albiflora Root Extract",
    "Palmitic Acid",
    "Palmitoyl Grape Seed Extract",
    "Palmitoyl Grapevine Shoot Extract",
    "Palmitoyl Hexapeptide-12",
    "Palmitoyl Tetrapeptide-7",
    "Palmitoyl Tripeptide-1",
    "Palmitoyl Tripeptide-38",
    "Palmitoyl Tripeptide-8",
    "Panax Ginseng Root Extract",
    "P-Anisic Acid",
    "Panthenol",
    "Paraffin",
    "Paraffinum Liquidum",
    "Paraffinum Liquidum Mineral Oil",
    "Paraffinum liquidum/mineral oil/huile minerale",
    "Passiflora Edulis Seed Oil",
    "PCA",
    "PEG-100 Stearate",
    "PEG-10 Dimethicone",
    "PEG-10 Isostearate",
    "PEG-10 Phytosterol",
    "PEG-120 Methyl Glucose Dioleate",
    "PEG-150",
    "PEG-150 Pentaerythrityl Tetrastearate",
    "PEG-20 Glyceryl Triisostearate",
    "PEG-30 Dipolyhydroxy Stearate",
    "PEG-30 Glyceryl Isostearate",
    "PEG-40 Hydrogenated Castor Oil",
    "PEG-45/Dodecyl Glycol Copolymer",
    "PEG-5 Pentaerythrityl Ether",
    "PEG-6 Caprylic/Capric Glycerides",
    "PEG-7 Glyceryl Cocoate",
    "PEG-8",
    "PEG-8 Stearate",
    "PEG-90 Glyceryl Isostearate",
    "PEG/PPG/Polybutylene Glycol-8/5/3 Glycerin",
    "Pelargonium Graveolens Flower Oil",
    "Pentaclethra Macroloba Oil",
    "Pentaerythrityl Tetra-di-t-butyl Hydroxyhydrocinnamate",
    "Pentaerythrityl Tetraethylhexanoate",
    "Pentaerythrityl Tetraisostearate",
    "Pentasodium Pentetate",
    "Pentylene Glycol",
    "Peppermint Oil",
    "Perilla Ocymoides Leaf Extract",
    "Persea Gratissima (Avocado) Fruit Extract",
    "Persea Gratissima Oil / Avocado Oil",
    "Petrolatum",
    "Phenethyl Alcohol",
    "Phenoxyethanol",
    "Phenoxyisopropanol",
    "Phenylalanine",
    "Phenylbenzimidazole Sulfonic Acid",
    "Phenyl Trimethicone",
    "Phospholipids",
    "Phragmites Kharka Extract",
    "Phytic Acid",
    "Phytosphingosine",
    "Phytosqualane",
    "Phytosterols",
    "Phytosteryl Canola Glycerides",
    "Phytosteryl/Isostearyl/Cetyl/Stearyl/Behenyl Dimer Dilinoleate",
    "Phytosteryl Macadamiate",
    "Pinus Sylvestris (Pine) Leaf Oil",
    "Plantago Lanceolata Leaf Extract",
    "Pleiogynium Timoriense Fruit Extract",
    "Plukenetia Volubilis Seed Oil",
    "Plumeria Alba Flower Extract",
    "Plumeria Rubra Flower Extract",
    "Podocarpus Elatus Fruit Extract",
    "Pogostemon Cablin Oil",
    "Polyacrylate Crosspolymer-6",
    "Polyamide-3",
    "Polyamide-8",
    "Polybutene",
    "Polyester-5",
    "Polyester-8",
    "Polyethylene",
    "Polyglutamic Acid",
    "Polyglycerin-3",
    "Polyglycerin-6",
    "Polyglyceryl-10 Dilaurate",
    "Polyglyceryl-10 Laurate",
    "Polyglyceryl-10 Stearate",
    "Polyglyceryl-2 Diisostearate/IPDI Copolymer",
    "Polyglyceryl-2 Dipolyhydroxystearate",
    "Polyglyceryl-2 Stearate",
    "Polyglyceryl 3 Beeswax",
    "Polyglyceryl-3 Caprate",
    "Polyglyceryl-3 Diisostearate",
    "Polyglyceryl-3 Distearate",
    "Polyglyceryl-3 Methylglucose Distearate",
    "Polyglyceryl-3 Polydimethylsiloxyethyl Dimethicone",
    "Polyglyceryl-3 Polyricinoleate",
    "Polyglyceryl-3 Stearate",
    "Polyglyceryl-4 Caprate",
    "Polyglyceryl-4 Laurate",
    "Polyglyceryl-6 Behenate",
    "Polyglyceryl-6 Laurate",
    "Polyglyceryl-6 Polyricinoleate",
    "Polyglyceryl-6 Stearate",
    "Polyhydroxystearic Acid",
    "Polyisobutene",
    "Polylysine",
    "Polymethyl Methacrylate",
    "Polymethylsilsesquioxane",
    "Polyquaternium-39",
    "Polyquaternium-51",
    "Polyquaternium-7",
    "Polyscsorbate",
    "Polysilicone-11",
    "Polysilicone-2",
    "Polysorbate 20",
    "Polysorbate 60",
    "Polysorbate 80",
    "Pongamia Glabra Seed Oil",
    "Pongamia Pinnata Seed Extract",
    "Populus Tremuloides Bark Extract",
    "Poria Cocos Extract",
    "Portulaca Oleracea Extract",
    "Portulaca Pilosa Extract",
    "Potassium Alum",
    "Potassium Cetyl Phosphate",
    "Potassium Chloride",
    "Potassium Hyaluronate",
    "Potassium Hydroxide",
    "Potassium Palmitoyl Hydrolyzed Wheat Protein",
    "Potassium Phosphate",
    "Potassium Sorbate",
    "PPG-17",
    "PPG-5-Ceteth-20",
    "PPG-5 Pentaerythrityl Ether",
    "PPG-6-Decyltetradeceth-20",
    "Proline",
    "Propanediol",
    "Propolis Extract",
    "Propylene Carbonate",
    "Propylene Glycol",
    "Propylheptyl Caprylate",
    "Propylparaben",
    "Prunus Amygdalus Dulcis Oil / Sweet Almond Oil",
    "Prunus Armeniaca Kernel Oil / Apricot Kernel Oil",
    "Ricinus Communis (Castor) Seed Oil",
    "Rosmarinus Officinalis (Rosemary) Leaf Extract",
    "Saccharide Isomerate",
    "Seaweed Extract",
    "Silica",
    "Simmondsia Chinensis (Jojoba) Seed Oil",
    "Sodium Benzoate",
    "Sodium Chloride",
    "Sodium Citrate",
    "Sodium Cocoamphoacetate",
    "Sodium Cocoate",
    "Sodium Cocoyl Glutamate",
    "Sodium Cocoyl Glycinate",
    "Sodium Cocoyl Isethionate",
    "Sodium Dilauramidoglutamide Lysine",
    "Sodium Gluconate",
    "Sodium Hyaluronate",
    "Sodium Hyaluronate Crosspolymer",
    "Sodium Hydroxide",
    "Sodium Isostearate",
    "Sodium Lactate",
    "Sodium Laurate",
    "Sodium Laureth Sulfate",
    "Sodium Lauroyl Aspartate",
    "Sodium Lauroyl Glutamate",
    "Sodium Lauroyl Lactylate",
    "Sodium Lauroyl Methyl Isethionate",
    "Sodium Lauroyl Sarcosinate",
    "Sodium Lauryl Glucose Carboxylate",
    "Sodium Lauryl Glycol Carboxylate",
    "Sodium Lauryl Sulfate",
    "Sodium Levulinate",
    "Sodium Magnesium",
    "Sodium Magnesium Silicate",
    "Sodium Metabisulfite",
    "Sodium Metaphosphate",
    "Sodium Methyl Cocoyl Taurate",
    "Sodium Methyl Oleoyl Taurate",
    "Sodium Panthenol",
    "Sodium PCA",
    "Sodium Phosphate",
    "Sodium Phytate",
    "Sodium Polyacrylate",
    "Sodium Polyacrylate Starch",
    "Sodium Polyacryloyldimethyl Taurate",
    "Sodium Saccharin",
    "Sodium Starch Octenylsuccinate",
    "Sodium Stearoyl Glutamate",
    "Sodium Sulfate",
    "Solanum Melongena (Eggplant) Fruit Extract",
    "Solanum Tuberosum (Potato) Pulp Extract",
    "Sorbic Acid",
    "Sorbitan Isostearate",
    "Sorbitan Laurate",
    "Sorbitan Oleate",
    "Sorbitan Oleate Decylglucoside Crosspolymer",
    "Sorbitan Olivate",
    "Sorbitan Sesquioleate",
    "Sorbitan Stearate",
    "Sorbitan Tristearate",
    "Sorbitol",
    "Sphingolipids",
    "Spirulina Platensis Extract",
    "Squalane",
    "Squalene",
    "sr-Hydrozoan Polypeptide-1",
    "Stearalkonium Hectorite",
    "Stearic Acid",
    "Stearyl Alcohol",
    "Stearyl Caprylate",
    "Stearyl Dimethicone",
    "Stearyl Glycyrrhetinate",
    "Stearyl Heptanoate",
    "Stellaria Media (Chickweed) Extract",
    "Stevia",
    "Stevia Rebaudiana Extract",
    "Styrax Tonkinensis Resin Extract",
    "Styrene/Acrylates Copolymer",
    "Sucrose",
    "Sucrose Cocoate",
    "Sucrose Polystearate",
    "Sucrose Stearate",
    "Sucrose Tetrastearate Triacetate",
    "Sunflower Seed Oil",
    "Synthetic Beeswax",
    "Synthetic Fluorphlogopite",
    "Synthetic Wax",
    "Talc",
    "Tamarindus Indica Seed Gum",
    "Tapioca Starch",
    "T-Butyl Alcohol",
    "Terminalia Chebula Fruit Extract",
    "Terminalia Ferdinandiana Fruit Extract",
    "Terminalia Ferdinandiana Fruit Powder",
    "Terminalia Ferdinandiana Seed Oil",
    "Tetrahexyldecyl Ascorbate",
    "Tetrahydroxypropyl Ethylenediamine",
    "Tetraisostearate",
    "Tetrasodium EDTA",
    "Tetrasodium EOTA",
    "Tetrasodium Glutamate Diacetate",
    "Theobroma Cacao (Cocoa) Seed Butter",
    "Theobroma Cacao (Cocoa) Seed Extract",
    "Thermus Thermophillus Ferment",
    "Thiotaurine",
    "Threonine",
    "Thymol",
    "Thymus Serpyllum Extract",
    "Tin Oxide",
    "Titanium Dioxide",
    "Tocopherol",
    "Tocopheryl Acetate",
    "Tocopheryl Linoleate",
    "Tranexamic Acid",
    "Trehalose",
    "Tremella Fuciformis Polysaccharide",
    "Tremella Fuciformis Sporocarp Extract",
    "Triacetin",
    "Tribehenin",
    "Tridecane",
    "Tridecyl Neopentanoate",
    "Tridecyl Salicylate",
    "Tridecyl Trimellitate",
    "Triethanolamine",
    "Triethoxycaprylylsilane",
    "Triethylhexanoin",
    "Triglyceride",
    "Triheptanoin",
    "Trihydroxystearin",
    "Triolein",
    "Trisiloxane",
    "Trisodium EDTA",
    "Trisodium Ethylenediamine",
    "Trisodium Ethylenediamine Disuccinate",
    "Triticum Vulgare",
    "Tromethamine",
    "Turmeric Butter",
    "Undaria Pinnatifida Extract",
    "Undecane",
    "Undecylenic Glycerides",
    "Urea",
    "Urtica Dioica (Nettle) Leaf Extract",
    "Va/butyl Maleate/isobornyl Acrylate Copolymer",
    "Vaccinium Myrtillus Fruit Extract",
    "Vaccinuium Macrocarpon (Cranberry) Seed Oil",
    "Valine",
    "Vanilin",
    "Vinyl Dimethicone",
    "Violet 2 (CI 60725)",
    "Vitis Vinifera (Grape) Fruit Extract",
    "Vitis Vinifera (Grape) Seed Oil",
    "VP/Eicosene Copolymer",
    "Water",
    "Wheat Amino Acids",
    "Wheat Germ Glycerides",
    "Xanthan Gum",
    "Ximenia Americana Seed Oil",
    "Xylitol",
    "Xylitylglucoside",
    "Yellow 5 (Ci 19140)",
    "Yellow 6 (Ci 15985)",
    "Zea Mays (Corn) Oil",
    "Zea Mays (Corn) Starch",
    "Zinc Chamomilla Recutita Flower Extract",
    "Zinc Gluconate",
    "Zinc Oxide",
    "Zinc Oxide (Nano)",
    "Zinc PCA",
    "Zinc Ricinoleate",
    "Zinc Sulfate",
    "Zingiber Officinale (Ginger) Root Extract",
    "Zingiber Officinale (Ginger) Root Oil",
    "Ziziphus Jujuba Fruit Extract"
]

    def handle(self, *args, **kwargs):
        created_count = 0
        for name in self.BASE_INGREDIENT_NAMES:
            obj, created = BaseIngredient.objects.get_or_create(name=name)
            if created:
                created_count += 1
                self.stdout.write(f"Created base ingredient: {name}")
            else:
                self.stdout.write(f"Already exists: {name}")

        self.stdout.write(self.style.SUCCESS(f"Finished populating. Created {created_count} new base ingredients."))
