name: Auto Approve and Merge Dependabot PRs

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    pull-requests: write
    contents: write

jobs:
  auto-approve-and-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MERGE_METHOD: squash
            MERGE_LABELS: ""
            MERGE_COMMIT_MESSAGE: "pull-request-title"
            MERGE_FILTER_AUTHOR: "dependabot[bot]"
            MERGE_DELETE_BRANCH: "true"
